name: Build New Release

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: 6.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build --configuration Release
      run: dotnet build --no-restore
    - name: Test
      run: dotnet test --no-build --verbosity normal
    - name: Publish
      run: dotnet publish --configuration Release --self-contained -r linux-arm -o publish
    - name: Make Version Number
      run: echo "NOW::$(date +'%Y%m%d.%H%M%S')" " ARM" >> $VERSION
    - name: Publish Release
    - uses: ncipollo/release-action@v1
      with:
        artifacts: publish
        generateReleaseNotes: true;
        name: $VERSION
        tag: $VERSION
        token: ${{ secrets.GITHUB_TOKEN }}
